# -*- coding: utf-8 -*-
"""cie1aiml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGBYiwZYnlPaMRXslZeABV0p0aZGh-vb
"""

import pandas as pd
data=pd.read_csv("/content/mtcars.csv")
data

import matplotlib.pyplot as plt
plt.hist(data['mpg'],bins=10,edgecolor='black')
plt.title('histogramof frequency')
plt.xlabel('mpg')
plt.ylabel('Frequency')
plt.title('Histogram of mpg')
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data['mpg'],data['wt'],edgecolor='black',alpha=0.7)
plt.grid(True)
plt.xlabel('weight')
plt.ylabel('milees pergallon')
plt.title('scatterplot:relation between carand mpg')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv("/content/mtcars.csv")
sns.barplot(x='model', y='mpg', data=data)
plt.xlabel("Model")
plt.ylabel("Miles per gallon")
plt.title("Barplot: MPG of Cars by Model")
plt.show()

import matplotlib.pyplot as plt
data.boxplot(column="mpg", by="model")
plt.xlabel("Model")
plt.ylabel("Miles per gallon")
plt.title("Boxplot: MPG of Cars by Model")
plt.show()